### ISSUE TITLE
Menu not working.

### ISSUE THREAD

**Issue by 19eighties** [getgrav/grav-skeleton-hpstr-site#2]
Just downloaded the skeleton and there is a javascript error.

```
Uncaught TypeError: $(...).dlmenu is not a function
```

**Comment by bipokot** [comment]
Confirm that. Tested in Chromium (Version 43.0.2357.0 (64-bit)) and Firefox (38.0.5).

> Uncaught TypeError: $(...).dlmenu is not a function(anonymous function) 
> @ scripts.min.js:1b.Callbacks.c 
> @ jquery.min.js:3b.Callbacks.p.fireWith 
> @ jquery.min.js:3b.extend.ready 
> @ jquery.min.js:3H 
> @ jquery.min.js:3

**Comment by bipokot** [comment]
Disabling debugger in `user/config/system.yaml` solved the problem.

```
debugger:
  enabled: false
```

**Comment by rhukster** [comment]
Was an issue with newer jquery.. Should be sorted now

**Comment by martn234** [comment]
hi, i am facing this issue. this issue occurs in some pages.

(index):1365 Uncaught TypeError: $(...).dlmenu is not a function
    at HTMLDocument.<anonymous> ((index):1365)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at Function.ready (jquery-1.11.0.min.js:2)
    at HTMLDocument.K (jquery-1.11.0.min.js:2)

please suggest me what to do with this?
