### ISSUE TITLE
Home menu item not going anywhere

### ISSUE THREAD

**Issue by spacemonkey** [getgrav/grav-skeleton-hpstr-site#3]
Just installed the skeleton and the `Home` item in the menu doesn't go anywhere. All of the other menu items appear to work fine though.

Trying with:
- Chrome Version 46.0.2490.71 (64-bit)
- Safari Version 9.0 (10601.1.56.2)

**Comment by rhukster** [comment]
This  is actually from the theme:

https://github.com/getgrav/grav-theme-hpstr/blob/develop/templates/partials/navigation.html.twig#L4

can you try changing this line to:

```
<li><a href="{{ base_url_relative ?: '/' }}">Home</a></li>
```

**Comment by spacemonkey** [comment]
That was the issue, your fix passes - you got this from here?

**Comment by rhukster** [comment]
Sure, in the future a PR would be helpful :)
